/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.java.eight.training.unit.one;

import org.junit.jupiter.api.Test;

import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static org.junit.jupiter.api.Assertions.*;

class Unit1Test {
    @Test void happyTesting() {

    }
}
